catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import MoviesListView, DetailView, ConfirmReservation, ReserveTicket, ConfirmationHandler, MyTickets, \
    DeleteTicketView

urlpatterns = [
    path("", MoviesListView.as_view(), name="movies-list"),
    path("<int:pk>/", DetailView.as_view(), name="movie-details"),
    path(
        "confirm_pay/<int:pk>", ConfirmReservation.as_view(), name="confirm_pay"
    ),
    path("reserve-ticket", ReserveTicket.as_view(), name="reserve_ticket"),
    path(
        "confirm_handler", ConfirmationHandler.as_view(), name="confirm_handler"
    ),
    path("my_tickets", MyTickets.as_view(), name="my_tickets"),
    path(
        "my_tickets/<int:pk>/delete",
        DeleteTicketView.as_view(),
        name="my_tickets_delete",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("articles/", include("articles.urls")),
    path("feedbacks/", include("feedbacks.urls")),
    path("movies/", include("catalog.urls")),
    path("admin/", admin.site.urls),
    path("", include("info.urls")),
    path("", include("authentication.urls")),
    path("admin_tools_stats/", include("admin_tools_stats.urls")),
]

info/urls.py
from django.urls import path

from .views import MainPageTemplateView, PrivacyPolicyTemplateView, AboutUsTemplateView, FAQsTemplateView, \
    ContactsListView, VacanciesTemplateView, CouponsTemplateView, AdditionalTemplateView

urlpatterns = [
    path("", MainPageTemplateView.as_view(), name="main-page"),
    path("privacy-policy", PrivacyPolicyTemplateView.as_view(), name="privacy-policy"),
    path("about-us", AboutUsTemplateView.as_view(), name="about-us"),
    path("faqs", FAQsTemplateView.as_view(), name="faqs"),
    path("contacts", ContactsListView.as_view(), name="contacts"),
    path("vacancies", VacanciesTemplateView.as_view(), name="vacancies"),
    path("coupons", CouponsTemplateView.as_view(), name="coupons"),
    path("additional", AdditionalTemplateView.as_view(), name="additional"),
]

catalog/models.py
from django.db import models
from django.utils import timezone


class Movie(models.Model):
    title = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    duration = models.DurationField()
    genre = models.ManyToManyField("Genre", help_text="choose genre")
    budget = models.CharField(max_length=200)
    poster = models.ImageField(upload_to="static/catalog/posters/")
    description = models.TextField()
    rating = models.FloatField()
    year_of_production = models.CharField(max_length=4)

    def __str__(self):
        return self.title


class MovieSession(models.Model):
    movie = models.ForeignKey("Movie", on_delete=models.CASCADE)
    date = models.DateField()
    time_begin = models.TimeField()
    lounge = models.ForeignKey("Lounge", on_delete=models.CASCADE)
    price_per_ticket = models.FloatField(default=10.0)

    def is_valid(self):
        return (
                self.date >= timezone.now().date()
                and self.payment_set.count() < self.lounge.capacity
        )

    def __str__(self):
        return self.movie.title


class Genre(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Lounge(models.Model):
    number = models.IntegerField()
    capacity = models.IntegerField()

    def __str__(self):
        return self.number.__str__()


class Payment(models.Model):
    userId = models.IntegerField()
    movie_session = models.ForeignKey("MovieSession", on_delete=models.CASCADE)
    PAY_STATUS = (
        ("p", "Pending"),
        ("s", "Success"),
        ("d", "Declined"),
    )

    status = models.CharField(
        max_length=1,
        choices=PAY_STATUS,
        blank=True,
        default="p",
    )

    def __str__(self):
        return self.status

catalog/forms.py
from django import forms


class ReserveTicketForm(forms.Form):
    session_id = forms.IntegerField(min_value=1)


class ConfirmTicketForm(forms.Form):
    payment_id = forms.IntegerField(min_value=1)

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic

from .forms import ReserveTicketForm, ConfirmTicketForm
from .models import Movie, Payment, MovieSession
from .services import get_random_dog, get_random_joke


class MoviesListView(generic.ListView):
    template_name = "catalog/movies-list.html"
    context_object_name = "movies_list"

    def get_queryset(self):
        query = Movie.objects.get_queryset()
        search = self.request.GET.get("search")
        genre = self.request.GET.get("genre")

        if search:
            query = query.filter(title__icontains=search)

        if genre:
            query = query.filter(genre__name__icontains=genre)

        return query.order_by("-year_of_production")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search"] = self.request.GET.get("search")
        context["genre"] = self.request.GET.get("genre")
        context["random_dog"] = get_random_dog()
        context["random_joke"] = get_random_joke()
        return context


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Movie
    template_name = "catalog/movie-details.html"
    login_url = reverse_lazy("login")


class ReserveTicket(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        form = ReserveTicketForm(self.request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            session = get_object_or_404(MovieSession, pk=form_data.get("session_id"))

            new_payment = Payment(userId=self.request.user.id, movie_session=session)
            new_payment.save()
            return f'/movies/confirm_pay/{new_payment.id}'


class ConfirmReservation(generic.DetailView):
    model = Payment
    template_name = "catalog/confirm_pay.html"


class ConfirmationHandler(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        form = ConfirmTicketForm(self.request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            payment = get_object_or_404(Payment, pk=form_data.get("payment_id"))
            if "cancel" in self.request.POST:
                payment.status = "d"
            else:
                payment.status = "s"
            payment.save()
        return reverse_lazy("movies-list")


class MyTickets(LoginRequiredMixin, generic.ListView):
    template_name = "catalog/my_tickets.html"
    context_object_name = "tickets_list"
    login_url = reverse_lazy("login")

    def get_queryset(self):
        return Payment.objects.filter(
            userId__exact=self.request.user.id, status__exact="s"
        ).all()


class DeleteTicketView(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        pk = kwargs.get("pk")
        if pk is not None:
            payment = Payment.objects.get(pk=pk)
            payment.delete()

        return reverse("my_tickets")

catalog/templates/catalog/confirm_pay.html
{%  extends 'base.html' %}
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static 'css/confirm_pay.css' %}">{% endblock %}
{% block title %}Purchase confirmation{% endblock %}
{% block content %}
    <h2>Confirm pay</h2>
    <form action="{% url 'confirm_handler' %}" method="post">
        {% csrf_token %}
        <input id="id_payment_id" name="payment_id" type="number" value="{{ payment.id }}" hidden="hidden"/>
        <input type="submit" value="Confirm"/>
        <input type="submit" value="Cancel" name="cancel"/>
    </form>
{% endblock %}

catalog/templates/catalog/movie-details.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/movie_details.css' %}">{% endblock %}
{% block title %}Home Page{% endblock %}
{% block content %}
    <section itemscope itemtype="https://schema.org/Movie" id="movie_details">
        <img itemprop="image" src="{{ movie.poster.url }}" alt="poster" height="600">
        <div id="movie_details_info">
            <h1 itemprop="name">{{ movie.title }}</h1>
            <p>Year: <span itemprop="datePublished">{{ movie.year_of_production }}</span></p>
            <p>Duration: <span itemprop="duration">{{ movie.duration }}</span></p>
            <p>Country: <span itemprop="countryOfOrigin">{{ movie.country }}</span></p>
            <p>IMDb score: <span itemprop="aggregateRating" itemscope
                                 itemtype="https://schema.org/AggregateRating"><span
                    itemprop="ratingValue">{{ movie.rating }}</span></span></p>
            <p>Budget: <span itemprop="budget">{{ movie.budget }}</span></p>
            <p>Genre:
                <span itemprop="genre">
                {% for ganr in movie.genre.all %}
                    <span>{{ ganr }}</span>{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </span>
            </p>
            <p itemprop="description">{{ movie.description }}</p>
        </div>
    </section>
    <section itemscope itemtype="https://schema.org/Event" id="available_sessions">
        <h2 itemprop="name">Available Movie Sessions</h2>
        <form id="coupon_form">
            <label for="coupon_input">Coupon: </label>
            <input type="number" id="coupon_input">
            <button id="coupon_submit">Apply</button>
        </form>
        <div class="all_tickets">
            {% for session in movie.moviesession_set.all %}
                {% if session.is_valid %}
                    <article itemprop="subEvent" itemscope itemtype="https://schema.org/ScreeningEvent" id="tickets">
                        <p><span itemprop="startDate" content="{{ session.date }}">{{ session.date }}</span></p>
                        <p>Lounge <span itemprop="location" itemscope itemtype="https://schema.org/Place"><span
                                itemprop="name">{{ session.lounge }}</span></span></p>
                        <p>Time the movie starts: <span itemprop="startDate"
                                                        content="{{ session.time_begin }}">{{ session.time_begin }}</span>
                        </p>
                        <p>Price <span itemprop="offers" itemscope itemtype="https://schema.org/Offer"><span
                                itemprop="priceCurrency" content="USD">$</span><span
                                itemprop="price" class="ticket_price">{{ session.price_per_ticket }}</span></span></p>
                        <form action="{% url 'reserve_ticket' %}" method="post">
                            {% csrf_token %}
                            <input id="id_session_id" name="session_id" type="number" value="{{ session.id }}"
                                   hidden="hidden"/>
                            <button type="submit">Buy ticket</button>
                        </form>
                    </article>
                {% endif %}
            {% endfor %}
        </div>
    </section>
    <script src="/static/scripts/coupons.js"></script>
{% endblock %}

catalog/templates/catalog/movies-list.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/movies.css' %}">{% endblock %}
{% block title %}Home Page{% endblock %}
{% block content %}
    <br>
    <section itemscope itemtype="https://schema.org/Movie">
        <h2 itemprop="name">Movies</h2>
        <form action="{% url 'movies-list' %}" method="get" id="search_group">
            <input name="search" type="text" placeholder="Search..." {% if search %} value="{{ search }}"{% endif %}>
            <input name="genre" type="text" placeholder="Search by genre..." {% if genre %}
                   value="{{ genre }}"{% endif %}>
            <button type="submit">Search</button>
        </form>
        <div id="movies_list">
            {% if movies_list %}
                {% for movie in movies_list %}
                    {% if movie.moviesession_set.count != 0 %}
                        <article itemprop="about" itemscope itemtype="https://schema.org/Article" id="movie">
                            <figure itemprop="image" itemscope itemtype="https://schema.org/ImageObject" id="poster">
                                <img alt="movie poster" data-src="{{ movie.poster }}" src="{{ movie.poster }}"
                                     itemprop="contentUrl">
                            </figure>
                            <h3 itemprop="name"><a href="{% url 'movie-details' movie.id %}"
                                                   itemprop="url">{{ movie.title }}</a></h3>
                            <meta itemprop="description" content="{{ movie.description }}">
                            <p>Genre:
                                <span itemprop="genre">
                                {% for genre in movie.genre.all %}
                                    <span itemprop="genre">{{ genre }}</span>{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </span>
                            </p>
                        </article>
                    {% endif %}
                {% endfor %}
            {% else %}
                <p>No movies are available.</p>
            {% endif %}
        </div>
    </section>
    {#    <footer itemscope itemtype="https://schema.org/WebPage">#}
    {#        <img itemprop="image" src="{{ random_dog }}" height="200" alt="random dog">#}
    {#        <p></p>#}
    {#        <p>Random joke: <span itemprop="description">{{ random_joke }}</span></p>#}
    {#    </footer>#}
{% endblock %}

catalog/templates/catalog/my_tickets.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/my_tickets.css' %}">
{% endblock %}
{% block title %}Home Page{% endblock %}
{% block content %}
    <section itemscope itemtype="https://schema.org/ItemList">
        <h2 itemprop="name">My Tickets</h2>
        {% if tickets_list %}
            <div class="all_tickets">
                {% for ticket in tickets_list %}
                <article itemprop="itemListElement" itemscope itemtype="https://schema.org/Ticket" id="ticket">
                    <h2 itemprop="name">{{ ticket.movie_session.movie.title }}</h2>
                    <meta itemprop="description" content="Movie ticket for {{ ticket.movie_session.movie.title }}">
                    <p>
                        Lounge <span itemprop="location" itemscope itemtype="https://schema.org/Place"><span
                            itemprop="name">{{ ticket.movie_session.lounge.number }}</span></span>,
                        Date:
                        <time itemprop="startDate"
                              datetime="{{ ticket.movie_session.date }}">{{ ticket.movie_session.date }}</time>
                    </p>
                    <p>Price: <span itemprop="priceCurrency" content="USD">$</span><span
                            itemprop="price">{{ ticket.movie_session.price_per_ticket }}</span></p>
                    <form action="{% url 'my_tickets_delete' ticket.id %}">
                        {% csrf_token %}
                        <button type="submit">Delete ticket</button>
                    </form>
                </article>
            {% endfor %}
            </div>
        {% else %}
            <p>No tickets reserved yet.</p>
        {% endif %}
    </section>
{% endblock %}