cinema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("articles/", include("articles.urls")),
    path("feedbacks/", include("feedbacks.urls")),
    path("movies/", include("catalog.urls")),
    path("admin/", admin.site.urls),
    path("", include("info.urls")),
    path("", include("authentication.urls")),
    path("admin_tools_stats/", include("admin_tools_stats.urls")),
]

feedbacks/urls.py
from django.urls import path

from .views import FeedbackListView, FeedbackCreateView

urlpatterns = [
    path("", FeedbackListView.as_view(), name="feedback-list"),
    path("create", FeedbackCreateView.as_view(), name="feedback-create"),
]

info/urls.py
from django.urls import path

from .views import MainPageTemplateView, PrivacyPolicyTemplateView, AboutUsTemplateView, FAQsTemplateView, \
    ContactsListView, VacanciesTemplateView, CouponsTemplateView, AdditionalTemplateView

urlpatterns = [
    path("", MainPageTemplateView.as_view(), name="main-page"),
    path("privacy-policy", PrivacyPolicyTemplateView.as_view(), name="privacy-policy"),
    path("about-us", AboutUsTemplateView.as_view(), name="about-us"),
    path("faqs", FAQsTemplateView.as_view(), name="faqs"),
    path("contacts", ContactsListView.as_view(), name="contacts"),
    path("vacancies", VacanciesTemplateView.as_view(), name="vacancies"),
    path("coupons", CouponsTemplateView.as_view(), name="coupons"),
    path("additional", AdditionalTemplateView.as_view(), name="additional"),
]

feedbacks/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone


class Feedback(models.Model):
    title = models.CharField(max_length=255)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f" {self.title} - {self.created_at}"

info/models.py
from django.db import models


class Worker(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    job_role = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=12)
    email_address = models.EmailField()
    photo = models.ImageField(upload_to="static/staff", default="static/logos/cinema_logo.png")

    def __str__(self):
        return self.last_name


class MapData(models.Model):
    date = models.DateField('date_add')
    key = models.CharField(max_length=255)

    def __str__(self):
        return self.date

feedbacks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from .models import Feedback


class FeedbackListView(ListView):
    template_name = "feedback-list.html"
    model = Feedback


class FeedbackCreateView(LoginRequiredMixin, CreateView):
    model = Feedback
    template_name = "feedback-create.html"
    fields = ("title", "rating", "content")
    success_url = reverse_lazy("feedback-list")
    login_url = reverse_lazy("login")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

feedbacks/templates/feedback-create.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/sign_up.css' %}">
{% endblock %}
{% block title %}Create feedback{% endblock %}

{% block content %}
    <section itemscope itemtype="https://schema.org/Review">
        <h2>Create New Feedback</h2>
        <form method="post" itemprop="reviewBody">
            {% csrf_token %}
            <p>
                <label for="id_title">Title:</label>
                <input type="text" name="title" maxlength="255" required="required" id="id_title" itemprop="name">
            </p>
            <p>
                <label for="id_rating">Rating:</label>
                <input type="number" name="rating" min="1" max="5" required="required" id="id_rating"
                       itemprop="reviewRating">
            </p>
            <p>
                <label for="id_content">Content:</label>
                <textarea name="content" id="id_content"></textarea>
            </p>
            <p>
                <label for="id_date">Content:</label>
                <input type="date" name="date" disabled id="id_date" itemprop="reviewRating">
            </p>
            <button type="submit">Save</button>
        </form>
    </section>
{% endblock %}

feedbacks/templates/feedback-list.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/feedback_list.css' %}">
{% endblock %}
{% block title %}Feedbacks{% endblock %}

{% block content %}
    <h2>Feedbacks</h2>
    <form action="{% url 'feedback-create' %}">
        <button type="submit">New feedback</button>
    </form>
    <section itemscope itemtype="https://schema.org/ItemList">
        {% if not feedback_list %}
            <p>No feedbacks</p>
        {% endif %}
        {% for feedback in feedback_list %}
            <article itemprop="itemListElement" itemscope itemtype="https://schema.org/Review" class="feedback">
                <h2 itemprop="name">{{ feedback.title }}</h2>
                <meta itemprop="reviewRating" content="{{ feedback.rating }}">
                <h3>
                    Author: <span itemprop="author">{{ feedback.author }}</span> -
                    <time itemprop="datePublished">{{ feedback.created_at }}</time>
                </h3>
                {% if feedback.content != "" %}
                    <p itemprop="reviewBody">{{ feedback.content }}</p>
                {% endif %}
            </article>
        {% endfor %}
    </section>
{% endblock %}